### PR TITLE
Updated mygui sha1

### PR DESCRIPTION
**Pull request by jeffreyhaines**
I'm getting that sha1 for the mygui zip?

### CODE REVIEW

**Comment by jeffreyhaines** [comment]
This must be a change for OS X El Capitain. The file downloaded for El Capitain has a different sha1 then the sha1 for the rest of the os's.

**Comment by corristo** [comment]
@jeffreyhaines thanks! I don't think it has something to do with El Capitan, though. They just changed the file for some reason.

**Comment by corristo** [comment]
@jeffreyhaines yeah, confirmed, it has nothing to do with iOS version, they just changed file.

**Comment by jeffreyhaines** [comment]
OS X*, cool just wondering if the link was somehow sending different files for el capitain and Yosemite

**Pull request merged**
